In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../../../Alpha-Quant-Course/Data/FixTimeBars/AUDUSD_4H_Admiral_READY.csv")

In [3]:
def displacement_detection(df, type_range="standard", strengh=3, period=100):
    """
    This function calculates and adds a 'displacement' column to a provided DataFrame. Displacement is determined based on
    the 'candle_range' which is calculated differently according to the 'type_range' parameter. Then, it calculates the
    standard deviation of the 'candle_range' over a given period and sets a 'threshold'. If 'candle_range' exceeds this 'threshold',
    a displacement is detected and marked as 1 in the 'displacement' column.

    Parameters:
    df (pd.DataFrame): The DataFrame to add the columns to. This DataFrame should have 'open', 'close', 'high', and 'low' columns.
    type_range (str, optional): Defines how to calculate 'candle_range'. 'standard' calculates it as the absolute difference between
                                'close' and 'open', 'extremum' calculates it as the absolute difference between 'high' and 'low'.
                                Default is 'standard'.
    strengh (int, optional): The multiplier for the standard deviation to set the 'threshold'. Default is 3.
    period (int, optional): The period to use for calculating the standard deviation. Default is 100.

    Returns:
    pd.DataFrame: The original DataFrame, but with four new columns: 'candle_range', 'MSTD', 'threshold' and 'displacement'.

    Raises:
    ValueError: If an unsupported 'type_range' is provided.
    """
    df_copy = df.copy()

    # Choose your type_range
    if type_range == "standard":
        df_copy["candle_range"] = np.abs(df_copy["close"] - df_copy["open"])
    elif type_range == "extremum":
        df_copy["candle_range"] = np.abs(df_copy["high"] - df_copy["low"])
    else:
        raise ValueError("Put a right format of type range")

    # Compute the STD of the candle range
    df_copy["MSTD"] = df_copy["candle_range"].rolling(period).std()
    df_copy["threshold"] = df_copy["MSTD"] * strengh

    # Displacement if the candle range is above the threshold
    df_copy["displacement"] = np.nan
    df_copy.loc[df_copy["threshold"] < df_copy["candle_range"], "displacement"] = 1
    df_copy["variation"] = df_copy["close"] - df_copy["open"]

    # Specify the way of the displacement
    df_copy["green_displacement"] = 0
    df_copy["red_displacement"] = 0

    df_copy.loc[(df_copy["displacement"] == 1) & (0 < df_copy["variation"]), "green_displacement"] = 1
    df_copy.loc[(df_copy["displacement"] == 1) & (df_copy["variation"] < 0), "red_displacement"] = 1

    # Shift by one because we only know that we have a displacement at the end of the candle (BE CAREFUL)
    df_copy["green_displacement"] = df_copy["green_displacement"].shift(1)
    df_copy["red_displacement"] = df_copy["red_displacement"].shift(1)

    df_copy["high_displacement"] = np.nan
    df_copy["low_displacement"] = np.nan

    df_copy.loc[df_copy["displacement"] == 1, "high_displacement"] = df_copy["high"]
    df_copy.loc[df_copy["displacement"] == 1, "low_displacement"] = df_copy["low"]

    df_copy["high_displacement"] = df_copy["high_displacement"].fillna(method="ffill")
    df_copy["low_displacement"] = df_copy["low_displacement"].fillna(method="ffill")

    return df_copy

In [4]:
displacement_detection(df)

,time,open,high,low,close,tick_volume,spread,real_volume,low_time,high_time,candle_range,MSTD,threshold,displacement,variation,green_displacement,red_displacement,high_displacement,low_displacement
0,2015-02-06 00:00:00,0.77970,0.78590,0.77933,0.78280,18061,4,21357500000,2015-02-06 00:30:00,2015-02-06 02:30:00,0.00310,NaN,NaN,NaN,0.00310,NaN,NaN,NaN,NaN
1,2015-02-06 04:00:00,0.78276,0.78433,0.78117,0.78401,12310,4,14275000000,2015-02-06 04:30:00,2015-02-06 07:30:00,0.00125,NaN,NaN,NaN,0.00125,0.0,0.0,NaN,NaN
2,2015-02-06 08:00:00,0.78400,0.78428,0.78185,0.78374,18258,4,19015000000,2015-02-06 10:00:00,2015-02-06 08:00:00,0.00026,NaN,NaN,NaN,-0.00026,0.0,0.0,NaN,NaN
3,2015-02-06 12:00:00,0.78374,0.78760,0.77793,0.78295,30785,4,32049500000,2015-02-06 15:30:00,2015-02-06 14:30:00,0.00079,NaN,NaN,NaN,-0.00079,0.0,0.0,NaN,NaN
4,2015-02-06 16:00:00,0.78295,0.78322,0.77851,0.77940,37224,4,41075000000,2015-02-06 16:00:00,2015-02-06 17:00:00,0.00355,NaN,NaN,NaN,-0.00355,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12511,2023-02-22 12:00:00,0.68211,0.68477,0.68149,0.68304,16249,4,0,2023-02-22 12:00:00,2023-02-22 14:30:00,0.00093,0.001545,0.004634,NaN,0.00093,0.0,0.0,0.70104,0.69436
12512,2023-02-22 16:00:00,0.68304,0.68378,0.68085,0.68225,24241,4,0,2023-02-22 17:30:00,2023-02-22 16:30:00,0.00079,0.001540,0.004619,NaN,-0.00079,0.0,0.0,0.70104,0.69436
12513,2023-02-22 20:00:00,0.68224,0.68319,0.67946,0.68049,18562,4,0,2023-02-22 21:30:00,2023-02-22 21:00:00,0.00175,0.001538,0.004614,NaN,-0.00175,0.0,0.0,0.70104,0.69436
12514,2023-02-23 00:00:00,0.68040,0.68340,0.67968,0.68324,7734,4,0,2023-02-23 00:00:00,2023-02-23 03:30:00,0.00284,0.001542,0.004625,NaN,0.00284,0.0,0.0,0.70104,0.69436
12515,2023-02-23 04:00:00,0.68322,0.68419,0.68188,0.68231,9418,4,0,2023-02-23 07:30:00,2023-02-23 05:00:00,0.00091,0.001544,0.004631,NaN,-0.00091,0.0,0.0,0.70104,0.69436