In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("../../../Alpha-Quant-Course/Data/FixTimeBars/AUDUSD_4H_Admiral_READY.csv")

In [6]:
def spread(df):
    """
    Calculates the spread between the 'high' and 'low' columns of a given DataFrame 
    and adds it as a new column named 'spread'.

    Parameters:
    -----------
    df : pandas.DataFrame
        The DataFrame containing the 'high' and 'low' columns for which the spread is to be calculated.

    Returns:
    --------
    df_copy : pandas.DataFrame
        A new DataFrame with the 'spread' column added.
    """
    df_copy = df.copy()
    df_copy["spread"] = df_copy["high"] - df_copy["low"]
    
    return df_copy

In [7]:
spread(df)

,time,open,high,low,close,tick_volume,spread,real_volume,low_time,high_time
0,2015-02-06 00:00:00,0.77970,0.78590,0.77933,0.78280,18061,0.00657,21357500000,2015-02-06 00:30:00,2015-02-06 02:30:00
1,2015-02-06 04:00:00,0.78276,0.78433,0.78117,0.78401,12310,0.00316,14275000000,2015-02-06 04:30:00,2015-02-06 07:30:00
2,2015-02-06 08:00:00,0.78400,0.78428,0.78185,0.78374,18258,0.00243,19015000000,2015-02-06 10:00:00,2015-02-06 08:00:00
3,2015-02-06 12:00:00,0.78374,0.78760,0.77793,0.78295,30785,0.00967,32049500000,2015-02-06 15:30:00,2015-02-06 14:30:00
4,2015-02-06 16:00:00,0.78295,0.78322,0.77851,0.77940,37224,0.00471,41075000000,2015-02-06 16:00:00,2015-02-06 17:00:00
...,...,...,...,...,...,...,...,...,...,...
12511,2023-02-22 12:00:00,0.68211,0.68477,0.68149,0.68304,16249,0.00328,0,2023-02-22 12:00:00,2023-02-22 14:30:00
12512,2023-02-22 16:00:00,0.68304,0.68378,0.68085,0.68225,24241,0.00293,0,2023-02-22 17:30:00,2023-02-22 16:30:00
12513,2023-02-22 20:00:00,0.68224,0.68319,0.67946,0.68049,18562,0.00373,0,2023-02-22 21:30:00,2023-02-22 21:00:00
12514,2023-02-23 00:00:00,0.68040,0.68340,0.67968,0.68324,7734,0.00372,0,2023-02-23 00:00:00,2023-02-23 03:30:00
12515,2023-02-23 04:00:00,0.68322,0.68419,0.68188,0.68231,9418,0.00231,0,2023-02-23 07:30:00,2023-02-23 05:00:00